name: Push-to-EC2

# Trigger deployment only on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout the files
        uses: actions/checkout@v3  # Updated to v3 to address node12 deprecation

      # Step 2: Deploy files to EC2 using easingthemes/ssh-deploy
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}   # Ensure this is base64-encoded
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Run remote commands on EC2 using appleboy/ssh-action
      - name: Executing remote SSH commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}   # Ensure correct format of SSH key
          script: |
            # Check if Apache2 is running and install/start if necessary
            if ! systemctl is-active --quiet apache2; then
              sudo apt-get -y update
              sudo apt-get install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
            else
              echo "Apache2 is already running."
            fi

            # Remove old files from /var/www/html before moving new ones
            sudo rm -rf /var/www/html/*

            # Move new files to /var/www/html
            cd home
            sudo mv * /var/www/html
